theme: minima

plugins:
  - jekyll-feed

collections:
  publications:
    output: true
  courses:
    output: true
  softwares:
    output: true

menu: 
  Home:
    url: "index.html"
  Publications:
    url: "publications.html"
  Teaching:
    url: "teaching.html"
  Software:
    url: "software.html"
  Resume:
    url: "resume.html"

email: "p.shi@hud.ac.uk"
google: "https://scholar.google.com/citations?user=qQuCvmQAAAAJ&hl=en&oi=ao"