

theme: minima

plugins:
  - jekyll-feed
  - jekyll-last-modified-at



collections:
  publications:
    output: true
  courses:
    output: true
  softwares:
    output: true

menu: 
  Home:
    url: "index.html"
  Publications:
    url: "publications.html"
  Teaching:
    url: "teaching.html"
  Software:
    url: "software.html"
  Resume:
    url: "resume.html"

email: "p.shi@hud.ac.uk"
webpage: "http://peizhishi.github.io"
github: "http://www.github.com/peizhishi"
orcid: "https://orcid.org/0000-0001-6724-282X"
google: "https://scholar.google.com/citations?user=qQuCvmQAAAAJ&hl=en&oi=ao"
